### ISSUE TITLE
SMART Health Card QR code invalid?

### ISSUE THREAD

**Issue by mbirth** [Path-Check/paper-cred-demo#16]
The SHC QR code generated on the [EU DGC page](https://github.pathcheck.org/eu.dgc.html) doesn't seem to be valid. iOS's Camera app shows this as "Health" and when tapping it, Health complains about "Unable to Add Data".

![IMG_1249](https://user-images.githubusercontent.com/130302/151418117-59299e0e-a786-4740-bda4-6a5585a2acb9.PNG) ![IMG_1250](https://user-images.githubusercontent.com/130302/151418176-c5ad3b33-ac24-4184-8e85-4abb16673033.PNG)

Whereas the official [example QR codes](https://spec.smarthealth.cards/examples/) show up as "COVID-19 vaccination" in the Camera and can be added to Health just fine.

![IMG_1251](https://user-images.githubusercontent.com/130302/151418235-25552267-f841-4b35-ba8e-59d738de1fc4.PNG)

**Comment by vitorpamplona** [comment]
That's correct. The codes generated in our demo page should not work on any production app.

**Comment by mbirth** [comment]
Ah, I see. That's a good reason. Thanks for clarification.
