### ISSUE TITLE
certificate with invalid signature

### ISSUE THREAD

**Issue by Rensch02** [Path-Check/paper-cred-demo#4]
When I create a vaccination certificate using the website and enter it in the green passport, I get an error message: "Certificate with invalid signature". I ask for help

**Comment by vitorpamplona** [comment]
Hi @Rensch02 

The keys we use are just for the demonstration on the website. The green passport will only work with production keys. The makers for the Green Passport have to manually add production keys to their app in order to verify the QR correctly.

**Comment by Rensch02** [comment]
That means I have to change the „EU HC1 Credentials“ to the ones from the production. One thing i wondered is that 1 month ago the generated QR Code was fine and tagged as Valid.

**Comment by vitorpamplona** [comment]
Humm. Very strange. Did you try in other verifying apps or just this one? Is there any private info your the QR you are testing? If not, can you share it here?

**Comment by Rensch02** [comment]
![7830759A-9ABB-40FA-98A5-FC50280AF9B4](https://user-images.githubusercontent.com/57462408/131200249-28d16bd1-2611-4518-b1a2-180cfc21dc59.png)

It was just the normal Qr code i generated on the Website. Bur since one month rhe Qr code is not valid any more. Do you think that it is possible to correct that?

**Comment by vitorpamplona** [comment]
We need to figure out if they implemented any other checks on the information inside the QR or if it's something related to the signature itself.

**Comment by vitorpamplona** [comment]
But to be fair, production apps should not include our keys, since they are only for demo purposes and we don't want anyone creating fake QRs on the site that can be verified by production systems. So, this answer from the app is actually the correct answer.

**Comment by Rensch02** [comment]
I got an Original Covid Vaccination Qr code and decoded it to an json. So there are only the head an the body differnt but the middle part is the same as the generated qr code

**Comment by Rensch02** [comment]
> But to be fair, production apps should not include our keys, since they are only for demo purposes and we don't want anyone creating fake QRs on the site that can be verified by production systems. So, this answer from the app is actually the correct answer.

Thats right but i wondered why the App said that it is an Invalid Signature

**Comment by vitorpamplona** [comment]
> Thats right but i wondered why the App said that it is an Invalid Signature

If the app does not have our site's public key hard coded in it, then it will say Invalid Signature.  That's the correct procedure.

**Comment by Rensch02** [comment]
Simply said, the keys for encrypting and decrypting the QR code must be identical to get a valid result

**Comment by vitorpamplona** [comment]
Not identical. The key to sign is the private key. The key to verify is the public key. 2 very different keys. The verification procedure uses the public key to verify if the signature was signed by the private key.

**Comment by Rensch02** [comment]
Oh yes i forgot. That makes sense. Obly with the private key i can generate an valid Qr code
